---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Expose vars
      include_vars: "../roles/3scale/defaults/main.yml"
    - set_fact:
        threescale_wildcard_domain: "amp.{{ eval_app_host }}"
      when: eval_threescale_enable_wildcard_route
    - set_fact:
        threescale_wildcard_domain: "{{ eval_app_host }}"
      when: not eval_threescale_enable_wildcard_route
    -
      name: Install 3Scale
      include_role:
        name: 3scale
      vars:
        threescale_route_suffix: "{{ threescale_wildcard_domain }}"
        enable_wildcard_route: "{{ eval_threescale_enable_wildcard_route }}"
      tags: ['3scale']
      when: threescale

    - name: Install apicurito
      include_role:
        name: apicurito
      vars:
        apicurito_route_suffix: "{{ eval_app_host }}"
      tags: ['apicurito']
      when: apicurito

    - name: Expose vars
      include_vars: "../roles/apicurito/defaults/main.yml"
